In [1]:
import numpy as np

In [2]:
#1. Create a null vector of size 10 but the fifth value which is 1.
ar=np.zeros(10)
ar[4]=1
print(ar)

size=ar.size
print("\nsize",size)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

size 10


In [3]:
#2. Create a vector with values ranging from 10 to 49.
ar=np.arange(10,50)
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
ar=np.arange(0,9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
ar = np.array([1,2,0,0,4,0])

print("Original array:")
print(ar)

print("\nIndices of null elements:")
res = np.nonzero(ar == 0)
print(res)

Original array:
[1 2 0 0 4 0]

Indices of null elements:
(array([2, 3, 5], dtype=int64),)


In [6]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
ar=np.random.randn(10,10)
print(ar)

minimum =ar.min()

print("\nThe minimum value is", minimum)

maximum =ar.max()

print("\nThe maximum value is", maximum)

[[ 5.18429195e-01 -2.17469295e-01 -4.49256018e-01 -1.28871520e-02
  -5.81907222e-01  1.42943396e+00 -1.14739489e+00  5.49472667e-01
  -1.46439209e-01  8.20100557e-02]
 [-1.17418521e+00  6.11093002e-02 -3.85340835e-01  4.18694258e-01
  -5.07778815e-01 -1.25963610e+00  1.20189418e+00 -6.23742040e-01
  -1.23520859e-01  1.55636017e+00]
 [ 9.50427423e-01 -2.35559294e-01  8.96573972e-01  8.18807109e-01
   3.07488410e-01 -4.29385821e-01  5.54121492e-01  1.36875780e+00
   2.81320264e-01 -3.11177263e-01]
 [ 2.20530537e-01 -1.00481321e-01 -1.19310133e+00  8.34002261e-02
   8.19712428e-01  1.86592992e-01 -6.89243394e-01 -4.60407311e-01
  -1.98646043e-03  1.77689052e-01]
 [-2.55868052e+00  2.86656087e-01  1.87707089e-01 -1.02005036e+00
   1.66107791e+00 -9.13500149e-01 -3.02772806e-01  9.74430509e-01
  -1.96284750e-01  5.59295140e-01]
 [-2.04993550e+00  1.00649568e+00  3.53751540e-01 -1.52876617e+00
  -4.66574795e-01 -1.23808396e+00  9.89570841e-02 -1.03465622e+00
  -5.30660507e-01  4.37377432e-01

In [7]:
#6. Create a random vector of size 30 and find the mean value.
ar=np.random.random(30)
print(ar)

ne=ar.mean()
print("\nThe mean value is", ne)

[0.90493071 0.80194922 0.02685981 0.58490436 0.16779522 0.71251224
 0.61816597 0.07674815 0.99694608 0.87857768 0.20776253 0.87093793
 0.43799888 0.79663881 0.22425105 0.59694554 0.16364101 0.54331181
 0.09778007 0.51165934 0.91736348 0.12986588 0.6145924  0.38899135
 0.95927753 0.88163647 0.24181356 0.02477886 0.97967842 0.56172317]

The mean value is 0.5306679185540089
